[opcode]
imm = 1
add = 2
stk = 4
stm = 8
ldm = 16
jmp = 32
sys = 64

[registers]
a = 1
b = 2
c = 4
d = 8
s = 16
i = 32
f = 64

[flags]
L = 1
G = 2
E = 4
N = 8
Z = 16

[syscalls]
open = 1
read_code = 2
read_mem = 4
write = 8
sleep = 16
exit = 32

op_order = [0, 1, 2]